### ISSUE TITLE
.destroy() gives a new error 

### ISSUE THREAD

**Issue by biologyscience** [mfuu/sortable-dnd#10]
## What I'm trying to do:
- On a click of button, make a list having a bunch of list items.
- After adding the appropriate classes to the list, append the list to the only div present in the DOM.

(Removing the `current` class of the previous lists before appending the new list. Because I want the draggables to be the children of a list like this `<ul class="current yes"> </ul>` and also for further use cases in the code)

- Appending the newly made list to the div.
- Using the `.destroy()` function to clear the event listeners if any.
- Making a new sortable and assigning to the same variable as before.

## What is happening:
- At first there is no list in DOM.
- Clicking the button `create element` makes a list whose children are now draggable.
- When you click the `create element` button again, it should remove the class `current` from the old list and add a list which has a class `current` and also `yes`.
- Now the newly added list should be draggable as I have destroyed the old sortable and assigned it to a new one which is to the newly added list.
- But, the children of the newly added list is not draggable and I'm getting this Error.

<img src="https://cdn.discordapp.com/attachments/755414148183228506/1008243771269459988/unknown.png">

Thanks.

###### PS: I have checked for any silly mistakes like I had with the previous issue, and I suppose there is none.

**Comment by mfuu** [comment]
@biologyscience 
Hi, this problem has been resolved in the latest version, you can update your version to solve it

**Comment by biologyscience** [comment]
Awesome, works like a charm !
