### ISSUE TITLE
Error when list is empty

### ISSUE THREAD

**Issue by jb-alvarado** [mfuu/sortable-dnd#56]
O get this error on vue3-virtual-drag-list , but I think is related to this repo. 

When a list is empty, then this error comes in browser console:

```
Uncaught (in promise) Sortable-dnd: `el` must be an HTMLElement, not [object Null]
```

In my case, I use two lists, and I want to be able to drag and drop from one list to the other. But at the beginning the second list might be empty.

**Comment by mfuu** [comment]
@jb-alvarado What does the empty list look like? Can you provide an example code?

**Comment by jb-alvarado** [comment]
@mfuu, in simple [sandbox](https://codesandbox.io/p/devbox/hardcore-ace-vhnxws?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clujlp4i200072066ijwf83zs%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clujlp4i200022066ti82dshb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clujlp4i2000420667k93zcot%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clujlp4i2000620663vxm8d0j%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clujmbp5o01ka2066sd8oatbd%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%252C%2522sizes%2522%253A%255B52.19156253773467%252C47.80843746226533%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clujlp4i200022066ti82dshb%2522%253A%257B%2522id%2522%253A%2522clujlp4i200022066ti82dshb%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clujlp4i2000620663vxm8d0j%2522%253A%257B%2522id%2522%253A%2522clujlp4i2000620663vxm8d0j%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clujlp4i2000520668v7qfovu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clujlp4i2000520668v7qfovu%2522%257D%252C%2522clujlp4i2000420667k93zcot%2522%253A%257B%2522id%2522%253A%2522clujlp4i2000420667k93zcot%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clujlp4i2000320661kdtspkh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clujlp4i2000320661kdtspkh%2522%257D%252C%2522clujmbp5o01ka2066sd8oatbd%2522%253A%257B%2522id%2522%253A%2522clujmbp5o01ka2066sd8oatbd%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clujm976c01hf2066pk27e6ag%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clujm976c01hf2066pk27e6ag%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) I was not able to reproduce.

The error pops up in this project: [ffplayout-frontend](https://github.com/ffplayout/ffplayout-frontend/blob/5047800e755a7fbeb4c84d0dd4fbb58f3d340957/pages/player.vue#L128).
But I think it don't help you, because without backend configured and running, all lists are empty.

**Comment by jb-alvarado** [comment]
@mfuu now my [sandbox](https://codesandbox.io/p/devbox/hardcore-ace-vhnxws?file=%2Fapp.vue%3A63%2C10&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clujlp4i200072066ijwf83zs%2522%252C%2522sizes%2522%253A%255B83.34768568353067%252C16.65231431646933%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clujlp4i200022066ti82dshb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clujlp4i2000420667k93zcot%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clujlp4i2000620663vxm8d0j%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B54.2835085964814%252C45.7164914035186%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clujlp4i200022066ti82dshb%2522%253A%257B%2522id%2522%253A%2522clujlp4i200022066ti82dshb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clujqfggb00022066akhmm43i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A63%252C%2522startColumn%2522%253A10%252C%2522endLineNumber%2522%253A63%252C%2522endColumn%2522%253A10%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clujqfggb00022066akhmm43i%2522%257D%252C%2522clujlp4i2000620663vxm8d0j%2522%253A%257B%2522id%2522%253A%2522clujlp4i2000620663vxm8d0j%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clujlp4i2000520668v7qfovu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clujlp4i2000520668v7qfovu%2522%257D%252C%2522clujlp4i2000420667k93zcot%2522%253A%257B%2522id%2522%253A%2522clujlp4i2000420667k93zcot%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clujlp4i2000320661kdtspkh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clujlp4i2000320661kdtspkh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) code reproduce the error.

I just switch from app.vue to pages/index.vue and add also layouts/default.vue

**Comment by mfuu** [comment]
@jb-alvarado I will check it after the holiday

**Comment by mfuu** [comment]
@jb-alvarado Sorry for late reply. Please update to the latest version to see if it works
