### ISSUE TITLE
Sortable.destroy() is not a function :(

### ISSUE THREAD

**Issue by biologyscience** [mfuu/sortable-dnd#9]
I'm trying to destroy the events listened for the current draggable `x`, but it doesn't work.

## Steps to reproduce
- Use the code below.
- Use the code in a node environment.
- After the DOM has loaded, click on **sort** button (the drag works now)
- Now click the **destroy** button which should destroy the events with no errors.
- But an error pops on the console and the drag events are not cleared.

## CODE
```html
<html>
<head>
    <style>
        ul
        {
            list-style: none;
        }

        li
        {
            width: 100px;
            background-color: blueviolet;
            margin: 1em 0;
        }

        button
        {
            margin: 0 1em;
        }
    </style>
</head>
<body>
    <div>
        <ul>
            <li>1</li>
            <li>2</li>
            <li>3</li>
            <li>4</li>
            <li>5</li>
        </ul>
    </div>

    <button id="sort">sort</button>
    <button id="destroy">destroy</button>

    <script>
        const sort = require('sortable-dnd');

        let x;

        document.getElementById('sort').onclick = () =>
        {
            x = new sort(document.querySelector('ul'))
        };

        document.getElementById('destroy').onclick = () =>
        {
            x === undefined ? null : x.destory();
        };
    </script>
</body>
</html>
```

## ERROR
```
Uncaught TypeError: x.destory is not a function
```
PS: If the problem is fixed, I will change the declaration file regarding the method destroy if needed.

Thanks

**Comment by mfuu** [comment]
You used the wrong word with `destory`, it should be `destroy`

**Comment by biologyscience** [comment]
big oops, sorry for making a issue for this 😅
